version: "3.7" 
services:

  php:
    build:
      context: sge-entregas
    image: sge-entregas/ge-entregas-service-php
    container_name: sge-entregas-service
    ports:
      - "9000:9000"
    volumes:
      - "./sge-entregas/:/var/www/html/"
    command: composer install
    command: php -S 0.0.0.0:9000 -t public/api/
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sge_entregas_db
      DB_USERNAME: root
      DB_PASSWORD: 12345

    links:
      - mysql
    networks:
      - sge-network

  mysql:
    image: mysql:5.7
    container_name: sge-entregas-db
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./sge-entregas/criacao-banco-mysql/init.sql:/data/application/init.sql      
      - ./sge-entregas/mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'sge_entregas_db'
      #MYSQL_USER: 'root'
      #MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345'
    networks:
      - sge-network

volumes:
  mysql:

networks:
  sge-network:
    name: sgenetwork  