version: "3.7" 
services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - sge-network

  gsl-mensageria-kafka:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://gsl-mensageria-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - sge-network



  gsl-api-gateway-parceiros-quarkus:
    image: gsl/gsl-api-gateway-parceiros-quarkus:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: gsl-api-gateway-parceiros/producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    depends_on:
      - gsl-mensageria-kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: gsl-mensageria-kafka:9092
      quarkus.rest-client."org.acme.kafka.services.SgeEntregasService".url: http://gse-entregas-service-php:9000/
    ports:
      - "8080:8080"
    networks:
      - sge-network



  #gsl-api-gateway-monitor-quarkus:
  #  image: gsl/gsl-api-gateway-monitor-quarkus:1.0-${QUARKUS_MODE:-jvm}
  #  build:
  #    context: gsl-api-gateway-parceiros/processor
  #    dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
  #  depends_on:
  #    - gsl-mensageria-kafka
  #  environment:
  #    KAFKA_BOOTSTRAP_SERVERS: gsl-mensageria-kafka:9092
  #  ports:
  #    - "8088:8080"      
  #  networks:
  #    - sge-network




  gse-entregas-service-php:
    build:
      context: sge-entregas
    image: sge-entregas/ge-entregas-service-php
    #container_name: sge-entregas-service
    ports:
      - "9000:9000"
    volumes:
      - "./sge-entregas/:/var/www/html/"
    #php /var/www/html/public/mensageria/consumer.php  
    command: [
      "sh", "-c",
      "php -S 0.0.0.0:9000 -t public/api/"
    ]
    environment:
      DB_HOST: sge-entregas-db
      DB_PORT: 3306
      DB_DATABASE: sge_entregas_db
      DB_USERNAME: root
      DB_PASSWORD: 12345

    links:
      - sge-entregas-db
    networks:
      - sge-network


  sge-entregas-integracao-sgl-php:
    build:
      context: sge-entregas-integracao-sgl
    image: sge-entregas/ge-entregas-integracao-sgl-php
    ports:
      - "9001:9000"
    volumes:
      - "./sge-entregas-integracao-sgl/:/var/www/html/"
    
    #command: [
    #  "sh", "-c",
    #  "php /var/www/html/public/mensageria/consumerToEndPoint.php"
    #]
    environment:
      services.SgeEntregasService.url: http://gse-entregas-service-php:9000/
    networks:
      - sge-network



  #gse-entregas-integracao-php:
  #  build:
  #    context: sge-entregas
  #  #image: sge-entregas/ge-entregas-service-php
  #  image: sge-entregas/ge-entregas-integracao-php
  #  #container_name: sge-entregas-integeracao
  #  ports:
  #    - "9001:9000"
  #  volumes:
  #    - "./sge-entregas/:/var/www/html/"
  #  
  #  command: [
  #    "sh", "-c",
  #    #"php /var/www/html/public/mensageria/consumer3.php"
  #    "php /var/www/html/public/mensageria/consumerToEndPoint.php"
  #  ]
  #  environment:
  #    DB_HOST: sge-entregas-db
  #    DB_PORT: 3306
  #    DB_DATABASE: sge_entregas_db
  #    DB_USERNAME: root
  #    DB_PASSWORD: 12345
#
  #    kafka.group.id: kafka-quickstart-producer'
  #    kafka.metadata.broker.list: 'gsl-mensageria-kafka'
  #    kafka.bootstrap.servers: 'gsl-mensageria-kafka:9092'
  #    kafka.auto.offset.reset: 'earliest'
  #    kafka.topic: 'relatorio-entrega-recebido'
  #    kafka.consume.timeout: 180000      
#
  #    services.SgeEntregasService.url: http://gse-entregas-service-php:9000/
#
  #  links:
  #    - sge-entregas-db
  #  networks:
  #    - sge-network



  sge-entregas-db:
    image: mysql:5.7
    container_name: sge-entregas-db
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./sge-entregas/criacao-banco-mysql/init.sql:/data/application/init.sql      
      - ./sge-entregas/mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'sge_entregas_db'
      #MYSQL_USER: 'root'
      #MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345'
    networks:
      - sge-network

volumes:
  mysql:

networks:
  sge-network:
    name: sgenetwork  