FROM php:7.4

RUN apt-get update && apt-get install -y \
    git \
    libc6-dev \
    libsasl2-dev \
    libsasl2-modules \
    libssl-dev \
    unzip

RUN apt-get update && apt-get -y --no-install-recommends install git \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install \
    && pecl install rdkafka \
    && docker-php-ext-enable rdkafka


RUN docker-php-ext-install pdo_mysql

RUN composer require arquivei/php-kafka-consumer

RUN composer install


WORKDIR /app
COPY . .

#ENTRYPOINT php /var/www/html/public/mensageria/consumer.php




    
